version: '3'
services:
  wrap_indexer:
    container_name: wrap_indexer
    build: .
    environment:
      ETHEREUM_NETWORK: "mainnet"
      ETHEREUM_NETWORK_ID: "1"
      ETHEREUM_RPC: ""
      ETHEREUM_WRAP_CONTRACT_ADDRESS: "0x5Dc76fD132354be5567ad617fD1fE8fB79421D82"
      ETHEREUM_FIRST_BLOCK_TO_INDEX: "14719029"
      ETHEREUM_CONFIRMATIONS_THRESHOLD: "12"
      TEZOS_NETWORK: "mainnet"
      TEZOS_QUORUM_CONTRACT: "KT1DLif2x9BtK6pUq9ZfFVVyW5wN2kau9rkW"
      TEZOS_MINTER_CONTRACT: "KT1MTnKjFSN2u4myPRBqnFuCYCPX8kTdUEnv"
      TEZOS_CONFIRMATIONS_THRESHOLD: "2"
      TEZOS_TZKT_API_URL: "https://api.tzkt.io/"
      TEZOS_RPC: "https://mainnet.smartpy.io/"
      IPFS_NODE: "http://wrap_ipfs:5001"
      POSTGRES_DB_USER: "wrap"
      POSTGRES_DB_PASSWORD: "wrap"
      POSTGRES_DB_HOST: "wrap_postgres"
      POSTGRES_DB_PORT: "5432"
      POSTGRES_DB_NAME: "indexer"
      HTTP_PORT: "3000"
      LOG_FORMAT: "pretty"
      LOG_LEVEL: "debug"
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - "wrap_postgres"
      - "wrap_ipfs"
    restart: unless-stopped
  wrap_postgres:
    container_name: wrap_postgres
    image: "postgres:13-alpine"
    environment:
      POSTGRES_USER: wrap
      POSTGRES_PASSWORD: wrap
      POSTGRES_DB: indexer
    volumes:
      - ./data-postgresql:/var/lib/postgresql/data
  wrap_ipfs:
    container_name: wrap_ipfs
    image: ipfs/go-ipfs:v0.8.0
    command: ["daemon", "--migrate=true", "--enable-pubsub-experiment", "--enable-namesys-pubsub"]
    volumes:
      - ./data-ipfs:/data/ipfs
